---
galaxy_info:
  role_name: authentik
  author: proegssilb
  description: Deploy Authentik identity provider via Docker Compose
  min_ansible_version: "2.14"
collections:
  - community.docker
  - community.general
  - ansible.posix
