apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubevirt/kubevirt/releases/download/0.53.0/kubevirt-operator.yaml
  - https://github.com/kubevirt/kubevirt/releases/download/0.53.0/kubevirt-cr.yaml
