repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
