apiVersion: v1
kind: Namespace
metadata:
  name: portainer
spec: {}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: portainer-repo
  namespace: portainer
spec:
  interval: 6h
  timeout: 6h
  url: https://portainer.github.io/k8s/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portainer-release
  namespace: portainer
spec:
  interval: 6h
  chart:
    spec:
      chart: portainer
      version: ">=1.0 <1.1"
      sourceRef:
        kind: HelmRepository
        name: portainer-repo
        namespace: portainer
      interval: 6h
  values:
    service:
      type: "ClusterIP"
    tls:
      force: True
    ingress:
      enabled: True
      ingressClassName: ""
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      hosts:
        - host: "crit.i.xenrelay.com"
          path: "/portainer"
