services:
  nextcloud:
    image: ghcr.io/proegssilb/nextcloud:main
    depends_on:
      - redis
      - pgdb
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "drive"
      tsdproxy.container_port: 80
    volumes:
      - nextcloud-app-data:/var/www/html
    ports:
      - 11000:80
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_HOST=pgdb
      - REDIS_HOST=redis
    networks:
      - nextcloud
      - swarm-macvlan

  pgdb:
    image: postgres:16
    volumes:
      - nextcloud-db:/var/vol/pgdata
    environment:
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DB}
      - PGDATA=/var/vol/pgdata/data
    networks:
      - nextcloud

  redis:
    image: redis:alpine
    volumes:
      - nextcloud-cache:/data
    networks:
      - nextcloud

volumes:
  nextcloud-db:
    external: true
  nextcloud-app-data:
    external: true
  nextcloud-cache:
    external: true

networks:
  nextcloud:
  swarm-macvlan:
    external: true
