version: "3.9"
services:
    postgres:
        image: postgres
        restart: unless-stopped
        ports:
            - target: 5432
              published: "5432"
              host_ip: 127.0.0.1
              protocol: tcp
              mode: host
        environment:
            - POSTGRES_DB=maas
            - POSTGRES_USER=maas
            - POSTGRES_PASSWORD_FILE=/run/secrets/dbpassword
        secrets:
            - dbpassword
    pgbackups:
        image: prodrigestivill/postgres-backup-local
        restart: unless-stopped
        user: postgres:postgres
        volumes:
            - /var/opt/pgbackups:/backups
        links:
            - postgres
        depends_on:
            - postgres
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_DB=maas
            - POSTGRES_USER=maas
            - POSTGRES_PASSWORD_FILE=/run/secrets/dbpassword
            - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
            - SCHEDULE=@daily
            - BACKUP_KEEP_DAYS=7
            - BACKUP_KEEP_WEEKS=4
            - BACKUP_KEEP_MONTHS=6
            - HEALTHCHECK_PORT=8080
        secrets:
            - dbpassword
secrets:
    dbpassword:
        environment: DB_PASSWORD
