---
- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
