---
- collections:
    - community.general
  hosts: all
  connection: local
  tasks:
    - name: "Power off"
      community.general.redfish_command:
        category: Systems
        command: PowerForceOff
        resource_id: 1
        baseuri: "{{ redfish_ip }}"
        username: "{{ redfish_user }}"
        password: "{{ redfish_pass }}"
    - name: "Mount image to virtual media"
      community.general.redfish_command:
        category: Manager
        command: VirtualMediaInsert
        baseuri: "{{ redfish_ip }}"
        username: "{{ redfish_user }}"
        password: "{{ redfish_pass }}"
        virtual_media:
          # TODO: Local mirror.
          image_url: 'https://releases.ubuntu.com/20.04/ubuntu-20.04.4-live-server-amd64.iso'
          media_types:
          - CD
          - DVD
        resource_id: 1
    - name: "Set next boot to virtual media"
      community.general.redfish_command:
        category: Systems
        command: SetOneTimeBoot
        resource_id: 1
        bootdevice: "UefiBootNext"
        boot_next: "CD/DVD"
        baseuri: "{{ redfish_ip }}"
        username: "{{ redfish_user }}"
        password: "{{ redfish_pass }}"
    - name: "Turn on"
      community.general.redfish_command:
        category: Systems
        command: PowerOn
        resource_id: 1
        baseuri: "{{ redfish_ip }}"
        username: "{{ redfish_user }}"
        password: "{{ redfish_pass }}"
