---
searxng_version: "2026.8.16-b2da6b90f"
searxng_data_disk: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi2
searxng_data_dir: /opt/searxng
searxng_port: 8080
searxng_secret_key: ""
searxng_base_url: ""
