#cloud-config

users:
  - name: minifig
    ssh_import_id:
      - ${pubkey}
    groups: users, admin, sudo
    shell: /usr/bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
  - name: sync
    system: false
    home: /home/sync
    groups: users
    shell: /usr/bin/bash
bootcmd:
  - "echo '127.0.0.1 ${hostname}' >> /etc/hosts"
runcmd:
  - "hostnamectl set-hostname ${hostname}"
  - "systemctl enable qemu-guest-agent"
  - "systemctl start qemu-guest-agent"
  - "curl -sSL https://install.pi-hole.net > /tmp/pihole-setup.sh"
  - "chmod +x /tmp/pihole-setup.sh"
  - "/tmp/pihole-setup.sh --unattended"
  #- "curl -sSL https://gravity.vmstan.com | bash"
write_files:
  - path: /etc/pihole/setupVars.conf
    owner: root:users
    permissions: '0640'
    content: |
      PIHOLE_INTERFACE=eth0
      PIHOLE_DNS_1=1.1.1.1
      PIHOLE_DNS_2=1.0.0.1
      QUERY_LOGGING=true
      INSTALL_WEB_SERVER=true
      INSTALL_WEB_INTERFACE=true
      LIGHTTPD_ENABLED=true
      CACHE_SIZE=10000
      DNS_FQDN_REQUIRED=true
      DNS_BOGUS_PRIV=true
      DNSMASQ_LISTENING=single
      WEBPASSWORD=5b73b5ee887737e8d21ac019366ff484fd3120a2a1c521f19ae43d7b66b7780e
      BLOCKING_ENABLED=true
  #- path: /etc/gravity-sync/gravity-sync.conf
    #owner: pihole:users
    #permissions: '0640'
    #content: |
      #REMOTE_HOST=${syncip}
      #REMOTE_USER='sync'

      ## CUSTOM VARIABLES ###########################

      ## Pi-hole Folder/File Customization - Only need to be customized when using containers
      ## LOCAL_PIHOLE_DIRECTORY=''                         # Local Pi-hole data directory
      ## REMOTE_PIHOLE_DIRECTORY=''                        # Remote Pi-hole data directory
      ## LOCAL_DNSMASQ_DIRECTORY=''                # Local DNSMASQ/FTL data directory
      ## REMOTE_DNSMASQ_DIRECTORY=''               # Remote DNSMASQ/FTL data directory
      ## LOCAL_FILE_OWNER=''                       # Local file owner for Pi-hole
      ## REMOTE_FILE_OWNER=''                      # Remote file owner for Pi-hole

      ## Pi-hole Docker/Podman container name - Docker will pattern match anything set below
      ## LOCAL_DOCKER_CONTAINER=''                                 # Local Pi-hole container name
      ## REMOTE_DOCKER_CONTAINER=''                            # Remote Pi-hole container name

      ## HIDDEN FIGURES #############################
      ## See https://github.com/vmstan/gravity-sync/wiki/Hidden-Figures
packages:
  - unattended-upgrades
  - qemu-guest-agent
package_update: true
package_upgrade: true
