#cloud-config

users:
  - name: minifig
    ssh_import_id:
      - gh:proegssilb
    groups: users, admin, sudo
    shell: /usr/bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
bootcmd:
  - "echo '127.0.0.1 ${hostname}' >> /etc/hosts"
runcmd:
  - "hostnamectl set-hostname ${hostname}"
  - "curl -sfL https://get.rke2.io | sh -"
  - "systemctl enable rke2-server.service"
  - "systemctl start rke2-server.service"
write_files:
%{ if kubemanifest != "" }
  - path: /var/lib/rancher/rke2/server/manifests/kube-manifest.yaml
    owner: root:root
    encoding: gz+b64
    defer: true
    content: ${kubemanifest}
%{ endif }
  - path: /etc/rancher/rke2/config.yaml
    owner: root:root
    encoding: gz+b64
    content: ${rkeconfig}
packages:
  - unattended-upgrades
  - qemu-guest-agent
package_update: true
package_upgrade: true
