---
_nginx_vhosts_apps:
  - name: forgejo
    server_name: "code.{{ homelab_domain }}"
    ssl_cert: "/etc/letsencrypt/live/{{ homelab_domain }}/fullchain.pem"
    ssl_key:  "/etc/letsencrypt/live/{{ homelab_domain }}/privkey.pem"
    upstream_protocol: http
    upstream_servers:
      - "forgejo.{{ homelab_domain }}:3000"

  - name: authentik
    server_name: "auth.{{ homelab_domain }}"
    ssl_cert: "/etc/letsencrypt/live/{{ homelab_domain }}/fullchain.pem"
    ssl_key:  "/etc/letsencrypt/live/{{ homelab_domain }}/privkey.pem"
    upstream_protocol: http
    upstream_servers:
      - "authentik.{{ homelab_domain }}:9000"

  - name: nextcloud
    server_name: "nc.{{ homelab_domain }}"
    ssl_cert: "/etc/letsencrypt/live/{{ homelab_domain }}/fullchain.pem"
    ssl_key:  "/etc/letsencrypt/live/{{ homelab_domain }}/privkey.pem"
    upstream_protocol: http
    upstream_servers:
      - "nextcloud.{{ homelab_domain }}:80"

  - name: budget
    server_name: "budget.{{ homelab_domain }}"
    ssl_cert: "/etc/letsencrypt/live/{{ homelab_domain }}/fullchain.pem"
    ssl_key:  "/etc/letsencrypt/live/{{ homelab_domain }}/privkey.pem"
    upstream_protocol: http
    upstream_servers:
      - "budget.{{ homelab_domain }}:5006"

  - name: mealie
    server_name: "mealie.{{ homelab_domain }}"
    ssl_cert: "/etc/letsencrypt/live/{{ homelab_domain }}/fullchain.pem"
    ssl_key:  "/etc/letsencrypt/live/{{ homelab_domain }}/privkey.pem"
    upstream_protocol: http
    upstream_servers:
      - "mealie.{{ homelab_domain }}:9000"

  - name: freshrss
    server_name: "rss.{{ homelab_domain }}"
    ssl_cert: "/etc/letsencrypt/live/{{ homelab_domain }}/fullchain.pem"
    ssl_key:  "/etc/letsencrypt/live/{{ homelab_domain }}/privkey.pem"
    upstream_protocol: http
    upstream_servers:
      - "freshrss.{{ homelab_domain }}:8080"

  - name: immich
    server_name: "photos.{{ homelab_domain }}"
    ssl_cert: "/etc/letsencrypt/live/{{ homelab_domain }}/fullchain.pem"
    ssl_key:  "/etc/letsencrypt/live/{{ homelab_domain }}/privkey.pem"
    upstream_protocol: http
    upstream_servers:
      - "immich.{{ homelab_domain }}:2283"
    extra_proxy_params: "client_max_body_size 10g;"

  - name: searxng
    server_name: "search.{{ homelab_domain }}"
    ssl_cert: "/etc/letsencrypt/live/{{ homelab_domain }}/fullchain.pem"
    ssl_key:  "/etc/letsencrypt/live/{{ homelab_domain }}/privkey.pem"
    upstream_protocol: http
    upstream_servers:
      - "searxng.{{ homelab_domain }}:8080"

  - name: ittools
    server_name: "tools.{{ homelab_domain }}"
    ssl_cert: "/etc/letsencrypt/live/{{ homelab_domain }}/fullchain.pem"
    ssl_key:  "/etc/letsencrypt/live/{{ homelab_domain }}/privkey.pem"
    upstream_protocol: http
    upstream_servers:
      - "ittools.{{ homelab_domain }}:8080"
