---
_nginx_vhosts_apps:
  - name: forgejo
    server_name: "code.{{ homelab_domain }}"
    ssl_cert: "/etc/letsencrypt/live/{{ homelab_domain }}/fullchain.pem"
    ssl_key:  "/etc/letsencrypt/live/{{ homelab_domain }}/privkey.pem"
    upstream_protocol: http
    upstream_servers:
      - "forgejo.{{ homelab_domain }}:3000"

  - name: authentik
    server_name: "auth.{{ homelab_domain }}"
    ssl_cert: "/etc/letsencrypt/live/{{ homelab_domain }}/fullchain.pem"
    ssl_key:  "/etc/letsencrypt/live/{{ homelab_domain }}/privkey.pem"
    upstream_protocol: http
    upstream_servers:
      - "authentik.{{ homelab_domain }}:9000"

  - name: nextcloud
    server_name: "nc.{{ homelab_domain }}"
    ssl_cert: "/etc/letsencrypt/live/{{ homelab_domain }}/fullchain.pem"
    ssl_key:  "/etc/letsencrypt/live/{{ homelab_domain }}/privkey.pem"
    upstream_protocol: http
    upstream_servers:
      - "nextcloud.{{ homelab_domain }}:80"
