---
_nginx_vhosts_platform:
  - name: proxmox
    server_name: "proxmox.{{ homelab_domain }}"
    ssl_cert: "/etc/letsencrypt/live/{{ homelab_domain }}/fullchain.pem"
    ssl_key:  "/etc/letsencrypt/live/{{ homelab_domain }}/privkey.pem"
    upstream_protocol: https
    upstream_servers: "{{ homelab_proxmox_nodes | map('regex_replace', '$', '.' + homelab_domain + ':8006') | list }}"
    sticky_cookie: PVEAuthCookie
