---
# tasks file for fetch-kubeconfig

- name: Fetch config
  fetch:
    src: /etc/rancher/rke2/rke2.yaml
    flat: true
    dest: "{{ local_path }}"
    fail_on_missing: true
  become: true
  when: first_host==1

- name: Replace IP Address
  delegate_to: localhost
  connection: local
  replace:
    path: "{{ local_path }}"
    regexp: '127\.0\.0\.1'
    replace: "{{ node_ip }}"
  when: first_host==1
