apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: flux-system
spec:
  interval: 12h
  chart:
    spec:
      chart: openebs
      version: '>=3.0.0 <4.0.0'
      sourceRef:
        kind: HelmRepository
        name: openebs-repo
        namespace: openebs
      interval: 6h
  values: {}
