# TODO: Figure out OS install...

- name: Set up passwordless sudo
  hosts: rke2_servers
  tasks:
    - lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
  become: yes
  tags:
    - sudoers
    - setup

- name: Install rke2
  hosts: rke2_servers
  any_errors_fatal: true
  become: yes
  roles:
    - role: rke2_server
  serial: 3
  tags: k8s

- name: Copy kubeconfig
  hosts: rke2_servers
  become: yes
  roles:
    - role: fetch_kubeconfig
      local_path: "/home/minifig/.kube/crit"
  tags:
    - flux
    - k8s
  
- name: Install flux
  hosts: localhost
  gather_facts: yes
  tasks:
    - command:
        cmd: 'flux bootstrap github --kubeconfig=/home/minifig/.kube/crit --owner=proegssilb --repository=homelab-infra --path=critical/flux --personal'
  tags:
    - flux
