apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph-external
  namespace: rook-ceph
spec:
  external:
    enable: true
  crashCollector:
    disable: true
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
  # optionally, the ceph-mgr IP address can be passed to gather metric from the prometheus exporter
  monitoring:
    enabled: true
    externalMgrPrometheusPort: 9283
    externalMgrEndpoints:
      - ip: 172.16.20.16
      - ip: 172.16.20.17
      - ip: 172.16.20.18
