apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/rook/rook/release-1.9/deploy/examples/crds.yaml
- https://raw.githubusercontent.com/rook/rook/release-1.9/deploy/examples/common.yaml
