apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cstor-release
  namespace: openebs
spec:
  interval: 6h
  chart:
    spec:
      chart: cstor
      version: ">=3.0 <4.0"
      sourceRef:
        kind: HelmRepository
        name: cstor-repo
        namespace: flux-system
      interval: 6h
  values: {}
